### ISSUE TITLE
Support for displaying English description of problems in leetcode-cn

### ISSUE THREAD

**Issue by taoweicn** [LeetCode-OpenSource/vscode-leetcode#389]
## 🚀 Feature Proposal

Thanks for your selfless contribution at first.
I wonder to know, is it possible to add a configuration to switch the language of leetcode-cn's problems, as it provides two languages:

![screenshot](https://user-images.githubusercontent.com/25795549/62934058-3c225c00-bdf6-11e9-91a3-159bcc77d555.png)

## Motivation

I want to use leetcode-cn in English problem description.

**Comment by hello2mao** [comment]
+1

**Comment by lintuming** [comment]
+1

**Comment by abowloflrf** [comment]
## and the problem title
![image](https://user-images.githubusercontent.com/17028350/67149302-5b4cd680-f2dc-11e9-8c05-7ac4afbb572e.png)
![image](https://user-images.githubusercontent.com/17028350/67149314-761f4b00-f2dc-11e9-950a-457bb8383051.png)

![image](https://user-images.githubusercontent.com/17028350/67149306-64d63e80-f2dc-11e9-8a61-f0cfb0f78d84.png)

**Comment by zxc2012** [comment]
+1

**Comment by jdneo** [comment]
Fixed by #690
