### ISSUE TITLE
How to config English filename when using leetcode-cn

### ISSUE THREAD

**Issue by GeekaholicLin** [LeetCode-OpenSource/vscode-leetcode#483]
Before you submit a question we recommend you to check out the [DOCUMENT](https://github.com/jdneo/vscode-leetcode/blob/master/README.md) first.

You can also find more information in:
- [TROUBLESHOOTING](https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting)
- [FAQ](https://github.com/jdneo/vscode-leetcode/wiki/FAQ)

## 💬 Questions and Help

The config `"filename": "${id}-${kebab-case-name}.${ext}"` generates the file with the Chinese problem name. Are there any ways to config the English filename when using leetcode-cn endpoint?

**Comment by hanxiaomax** [comment]
any follow up ?

**Comment by linconz** [comment]
same issue

**Comment by iiwowks** [comment]
same issue

**Comment by jdneo** [comment]
Now you can use the setting `leetcode.useEndpointTranslation` to switch between Chinese and English.
