### ISSUE TITLE
Can we use the problem name part in the URL to create the filename for leetcode-cn?

### ISSUE THREAD

**Issue by hanxiaomax** [LeetCode-OpenSource/vscode-leetcode#539]
## 🚀 Feature Proposal

For example, if we can fetch data from the URL:
https://leetcode-cn.com/problems/add-two-numbers/description/

why we don't use `add-two-numbers` as the filename instead of some Chinese characters? 

## Motivation

Using Chinese filename seem weird and inconvenient

**Comment by jdneo** [comment]
dup with https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/483, please use the setting `leetcode.useEndpointTranslation`

**Comment by uestc-alayi** [comment]
setting leetcode.useEndpointTranslation will change description language too, I need keep  description in chinese, but fileName would be english.
