### ISSUE TITLE
内网代理场景无法登录

### ISSUE THREAD

**Issue by viscar** [LeetCode-OpenSource/vscode-leetcode#540]
login: pass: - Signing in leetcode.com
(node:18912) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
[ERROR] Error: connect ETIMEDOUT 47.99.228.218:443
使用网页可以正常登录

**Comment by tiandaoyi** [comment]
You can try setting up VSCODE proxy

**Comment by jdneo** [comment]
Please try the solution @tiandaoyi proposed. And let us know if the problem still occur.
