### ISSUE TITLE
leetcode-cn.com account can not sign in with Error: certificate has expired

### ISSUE THREAD

**Issue by kbkbks** [LeetCode-OpenSource/vscode-leetcode#563]
## 🐛 Bug Report

leetcode-cn.com account can not sign in.

## To Reproduce

1. Sign in to LeetCode (EndPoint has been switched to China).
2. Choose sign in method, Leetcode Account.
3. Enter the username and password (Enter the E-mail will have the same problem).
4. Can not sign in with Error: certificate has expired.

## Expected behavior

Sign in leetcode-cn.com correctly.

## Extension Output

![2020-05-31 03-40-47屏幕截图](https://user-images.githubusercontent.com/42246410/83337831-1e74a380-a2f1-11ea-93b3-b26a235e54b5.png)

## Your Environment

- *os*: Ubuntu 18.04.4 LTS
- *extension settings*: default
- *nodejs version*: v8.10.0
- *vscode version*: 1,45,1
- *extension version*: 0.16.2

**Comment by alexzhangwhu** [comment]
+1

**Comment by yihong0618** [comment]
Let me check it later today.

**Comment by pastqing** [comment]
+1

**Comment by nslyc** [comment]
how's it going,my friend.

**Comment by kbkbks** [comment]
> @nslyc 
> how's it going,my friend.

Still can not sign in.

**Comment by jdneo** [comment]
@all

Will it work if using the cookie login? See: https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/478#issuecomment-571821132

**Comment by yihong0618** [comment]
@jdneo I think its not match leetcode-cn, leetcode-cn use a different way store cookie.

**Comment by dageita** [comment]
+1

**Comment by yihong0618** [comment]
@ALL
For now it seems only GitHub way to loging can be used, and LinkedIn way is on the way,see https://github.com/leetcode-tools/leetcode-cli/pull/43 for leetcode-cn and I will work on this tonight, but I think leetcode-cn is using graphql which is a little complicated, I need some time.

And if you want login you can try link GitHub and login, and make sure you have at least login once for your computer.

**Comment by bailongxian** [comment]
acount login way  still not available

**Comment by JohnnyWei188** [comment]
yeah, i have the same problem with account login...
```
login: pass: - Signing in leetcode-cn.com
[ERROR] Error: certificate has expired
```

**Comment by jdneo** [comment]
That's wired. I tested locally and can login to `leetcode.cn`.

@yihong0618 Can you login to leetcode.cn?

**Comment by yihong0618** [comment]
> That's wired. I tested locally and can login to `leetcode.cn`.
> 
> @yihong0618 Can you login to leetcode.cn?

Yes old account is fine using vscode-leetcode, I have tested, but when you use a new account all methods can not. You can try use leetcode-cli using a new terminal for test, or you can sign up a new account .

**Comment by jdneo** [comment]
Thanks @yihong0618 

what do you mean by `new terminal`? I mean, what's the difference between new and old terminal?

**Comment by yihong0618** [comment]
@jdneo 
Like you do not use vscode-leetcode just leetcode-cli and use a new computer or something to try to login.

**Comment by border** [comment]
+1 
have the same problem, leetcode-cn.com certificate has expired.

**Comment by yihong0618** [comment]
@All @jdneo 
I have kind of solved these problem. Please help me to check. Its not the api problem, but its node tls problem.
Please check your node version if it version <= 8.13 the when leetcode interact with node, it will cause the problem. See https://github.com/firebase/firebase-tools/issues/1901
---
If you do not know how to update you can try this https://stackoverflow.com/questions/10075990/upgrading-node-js-to-latest-version

**Comment by dageita** [comment]
thanks @yihong0618, which solved this error!

**Comment by yihong0618** [comment]
@dageita  Its too wired. - -

**Comment by dageita** [comment]
@yihong0618 I have nodejs v8.17.0 on centos7.5, but it still needs to update.

**Comment by yihong0618** [comment]
> @yihong0618 I have nodejs v8.17.0 on centos7.5, but it still needs to update.

can you help me find which is minal? I update to 14.3 ...

**Comment by dageita** [comment]
> > @yihong0618 I have nodejs v8.17.0 on centos7.5, but it still needs to update.
> 
> can you help me find which is minal? I update to 14.3 ...

I also update to 14.3 😀

**Comment by yihong0618** [comment]
> > > @yihong0618 I have nodejs v8.17.0 on centos7.5, but it still needs to update.
> > 
> > 
> > can you help me find which is minal? I update to 14.3 ...
> 
> I also update to 14.3 😀

Minimal  seems 10.

**Comment by Maxwell-Lyu** [comment]
> @ALL @jdneo
> I have kind of solved these problem. Please help me to check. It is not the api problem, but its node `tls` problem.
> Please check your node version if it version <= 10 , when leetcode-api interact with node, it will cause the problem. See [firebase/firebase-tools#1901](https://github.com/firebase/firebase-tools/issues/1901)
> 
> If you do not know how to update node you can try this https://stackoverflow.com/questions/10075990/upgrading-node-js-to-latest-version

This solves my problem.
Ubuntu 18.04, upgrading nodejs to latest stable version solves the problem
+ what I have done
``` bash
sudo npm install n -g
sudo n stable
```
[Reference to Stackoverflow](https://stackoverflow.com/questions/10075990/upgrading-node-js-to-latest-version)

**Comment by zhiyuzhao** [comment]
@yihong0618  I upgrade my node by nvm, but still occur 'certificate has expired' error.
I found my vscode output still printed v8.9.0. Which node the extension use? I check the node version in terminal, alread upgrade succsess.
![image](https://user-images.githubusercontent.com/8134511/83624840-bb6f5f00-a5c5-11ea-96ee-d8e6e57b40ec.png)
![image](https://user-images.githubusercontent.com/8134511/83624860-c1fdd680-a5c5-11ea-9ecf-4511df0efac7.png)

**Comment by yihong0618** [comment]
> @yihong0618 I upgrade my node by nvm, but still occur 'certificate has expired' error.
> I found my vscode output still printed v8.9.0. Which node the extension use? I check the node version in terminal, alread upgrade succsess.
> ![image](https://user-images.githubusercontent.com/8134511/83624840-bb6f5f00-a5c5-11ea-96ee-d8e6e57b40ec.png)
> ![image](https://user-images.githubusercontent.com/8134511/83624860-c1fdd680-a5c5-11ea-9ecf-4511df0efac7.png)

see this
https://stackoverflow.com/questions/44700432/visual-studio-code-to-use-node-version-specified-by-nvm

**Comment by zhiyuzhao** [comment]
THX  it's work!

**Comment by xoyolucas** [comment]
Thanks a lot!

**Comment by liran319** [comment]
I notice  that vscode-leetcode plugin requires a Node version newer than 10.0, so I manually fill in the leetcode-node path with a lts/erbium(Node v12.18.2), then I login successfully.

**Comment by yihong0618** [comment]
@jdneo can we add version check in vscode-leetcode init?
