### ISSUE TITLE
中国版无法登陆(leetcode-cn can't login)

### ISSUE THREAD

**Issue by ixysoft** [LeetCode-OpenSource/vscode-leetcode#568]
## 🐛 Bug Report
中国版无法正常登陆,显示证书过期.
## output:
login: pass: - Signing in leetcode-cn.com
[ERROR] Error: certificate has expired

**Comment by yihong0618** [comment]
see #563 
Update your node > 10

**Comment by jdneo** [comment]
Close for duplication
