### ISSUE TITLE
Log in Failure on leetcode-cn account

### ISSUE THREAD

**Issue by EnderByEndera** [LeetCode-OpenSource/vscode-leetcode#576]
## 🐛 Bug Report

When logging in the leetcode-cn account with account and password, the LeetCode plugin told me that Error: certificate has expired.

## To Reproduce
After trying to log in twice, LeetCode plugin always told me that certificate has expired. I'm sure I entered the correct password and account for I've used the same password and account on the website.

## Expected behavior

I hope that if I use the password and account to log in, it will log in correctly, not showing some certificate has expired error.

## Extension Output
Here are the output loggings after I've tried to log in twice:

 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
[ERROR] You are not login yet?
login: pass: - Signing in leetcode-cn.com
[ERROR] Error: certificate has expired
login: pass: - Signing in leetcode-cn.com
[ERROR] Error: certificate has expired

## Your Environment

- *os*: Windows 10.0.18363
- *extension settings*: 
{
    "window.zoomLevel": 1,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "debug.onTaskErrors": "debugAnyway",
    "editor.renderWhitespace": "all",
    "editor.renderControlCharacters": true,
    "git.ignoreLegacyWarning": true,
    "C_Cpp.updateChannel": "Insiders",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "breadcrumbs.enabled": true,
    "diffEditor.ignoreTrimWhitespace": false,
    "workbench.colorTheme": "Solarized Dark",
    "cmake.configureOnOpen": true,
    "editor.largeFileOptimizations": false,
    "editor.quickSuggestions": true,
    "javascript.implicitProjectConfig.experimentalDecorators": true,
    "leetcode.defaultLanguage": "cpp",
    "leetcode.endpoint": "leetcode-cn",
    "leetcode.nodePath": "/usr/bin/node",
    "leetcode.workspaceFolder": "/home/endera/.leetcode",
    "leetcode.useWsl": true,
    "leetcode-cpp-debugger.source": "[online]leetcode-cn.com",
    "markdown.preview.breaks": true,
    "leetcode.hint.configWebviewMarkdown": false,
    "leetcode-cpp-debugger.outputFileEncoding": "utf8",
    "leetcode.editor.shortcuts": [
        "submit",
        "test",
        "solution",
        "description",
    ],
    "editor.fontSize": 12,
    "markdown.preview.fontSize": 12,
    "markdown.preview.lineHeight": 1.4,
    "leetcode.hint.commandShortcut": false,
}
- *nodejs version*: v8.10.0
- *vscode version*: 1.46.0 x64
- *extension version*: v0.16.2

**Comment by jdneo** [comment]
Please update your nodejs version to latest. See: https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/559

Close for duplication
