### ISSUE TITLE
I cannot use leetcode in Vscode

### ISSUE THREAD

**Issue by 118988577** [LeetCode-OpenSource/vscode-leetcode#578]
Before you submit an question we recommend you to check out the [DOCUMENT](https://github.com/jdneo/vscode-leetcode/blob/master/README.md) first.

You can also find more information in:
- [TROUBLESHOOTING](https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting)
- [FAQ](https://github.com/jdneo/vscode-leetcode/wiki/FAQ)

## 💬 Questions and Help
i cannot use leetcode inVScode,because it report  the question
[ERROR] Error: unable to verify the first certificate
Please outline the questions.

**Comment by jdneo** [comment]
What's your node version

**Comment by 118988577** [comment]
&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sheng Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 中午11:08
收件人:&nbsp;"LeetCode-OpenSource/vscode-leetcode"<vscode-leetcode@noreply.github.com&gt;;
抄送:&nbsp;"1018988577"<1018988577@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LeetCode-OpenSource/vscode-leetcode] I cannot use leetcode in Vscode (#578)





 
What's your node version

**Comment by jdneo** [comment]
Close since it's duplicated with #579

**Comment by kermit-ye** [comment]
v8.9.1
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ×     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ×     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ×     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   √     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ×     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
[ERROR] You are not login yet?
login: pass: .vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:589
    const authenticityToken = body.match(/name="authenticity_token" value="(.*?)"/);
                                   ^

TypeError: Cannot read property 'match' of undefined
    at Request._callback (.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:589:36)
    at self.callback (.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\request\request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
login: pass: - Signing in leetcode.com
[ERROR] Error: unable to verify the first certificate
login: pass: - Signing in leetcode.com
[ERROR] Error: unable to verify the first certificate
login: login: pass: - Signing in leetcode.com
[ERROR] Error: unable to verify the first certificate
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   √     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
[ERROR] You are not login yet?
login: login: login: pass: - Signing in leetcode-cn.com
[ERROR] Error: unable to verify the first certificate
