### ISSUE TITLE
Anyway to filter by tag and difficulty simultaneously?

### ISSUE THREAD

**Issue by parkershamblin** [LeetCode-OpenSource/vscode-leetcode#584]
## 💬 Questions and Help

Hello, is there anyway to filter the problems by tag and difficulty simultaneously? For example, if I wanted to only see Array problems with Medium difficulty is there anyway to do this?

Thanks,
Parker

**Comment by jdneo** [comment]
Hi @parkershamblin, 

I'm sorry it not supported yet. Not sure if VS Code has the APIs to let extensions provide a filter to the tree view. (as far as I know, it does not have). 

Anyway, we can definitely revisit this issue once there is such a API to do this.

Thanks
