### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by JayaHuang** [LeetCode-OpenSource/vscode-leetcode#585]
i cannot install the extension in vscode.
![image](https://user-images.githubusercontent.com/18739970/85887666-d2971a80-b81a-11ea-9b65-7f3989047cb3.png)

**Comment by jdneo** [comment]
@JayaHuang please try manually download the extension and install it. It should be something related with VS Code market place or your own environment.

**Comment by JayaHuang** [comment]
> @JayaHuang please try manually download the extension and install it. It should be something related with VS Code market place or your own environment.

![image](https://user-images.githubusercontent.com/18739970/85913225-5bd33f00-b865-11ea-8c29-65baee72cad8.png)
thanks for reply. 
it shows this info when i manually install the extension.

**Comment by jdneo** [comment]
The information is very clear, you need to update your VS Code to the latest.
