### ISSUE TITLE
Failed to list problems

### ISSUE THREAD

**Issue by TWSFar** [LeetCode-OpenSource/vscode-leetcode#589]
[ERROR] Error: connect ETIMEDOUT 104.18.35.28:443

my config:
![image](https://user-images.githubusercontent.com/24838179/86117653-fe0f5300-bb01-11ea-942b-535c9ccc7f3b.png)

line 51 is try solve from ＃320, but it like not work for new version vscode-leetcode, so i remove it.

can you help me?

. git version 2.24.0.windows.2
. node v14.4.0
. npm -v 6.14.5
. win10
. leetcode-cli install format: git clone + ./bin/install (show: leetcode-cli successfully installed.)

**Comment by jdneo** [comment]
Cannot repro using 0.17.0,

Please make sure your network is ok.

**Comment by TWSFar** [comment]
@jdneo 

> Cannot repro using 0.17.0,
> 
> Please make sure your network is ok.

![image](https://user-images.githubusercontent.com/24838179/86119198-a0303a80-bb04-11ea-8069-b1489df994b6.png)
My internet speed is not fast, so slow speed will cause this problem? It should be noted that I can use the leetcode-cn version. If it is not easy to solve, I can choose to use the cn version, I have to say that your work is great

**Comment by jdneo** [comment]
I guess it's caused by the network issue.
