### ISSUE TITLE
第三方node依赖，路径错误

### ISSUE THREAD

**Issue by woofhyx** [LeetCode-OpenSource/vscode-leetcode#590]
## 🐛 Bug Report

开启插件后，会读取.vscode-insiders目录下extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/config.js文件更新js文件，该文件中plugin字段路径错误，导致无法正常启动插件

## To Reproduce

code vs使用1.47.0，vscode-leetcode使用0.17.0，默认配置，会出现如下错误
```shell
$ proxychains node "/home/switch/.vscode-insiders/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/bin/leetcode"
[WARN] Installing missing plugins, might take a while ...
(node:10727) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
⠋ Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli-plugins/tree/master/plugins/cpp.lint.js[proxychains] Strict chain  ...  127.0.0.1:1088  ...  raw.githubusercontent.com:443  ...  OK
⠋ Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli-plugins/tree/master/plugins/cpp.run.js[proxychains] Strict chain  ...  127.0.0.1:1088  ...  raw.githubusercontent.com:443  ...  OK
⠋ Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli-plugins/tree/master/plugins/github.js[proxychains] Strict chain  ...  127.0.0.1:1088  ...  raw.githubusercontent.com:443  ...  OK
⠋ Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli-plugins/tree/master/plugins/lintcode.js[proxychains] Strict chain  ...  127.0.0.1:1088  ...  raw.githubusercontent.com:443  ...  OK
⠋ Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli-plugins/tree/master/plugins/cookie.chrome.js[proxychains] Strict chain  ...  127.0.0.1:1088  ...  raw.githubusercontent.com:443  ...  OK
⠋ Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli-plugins/tree/master/plugins/cookie.firefox.js[proxychains] Strict chain  ...  127.0.0.1:1088  ...  raw.githubusercontent.com:443  ...  OK
[ERROR] HTTP Error: 404
```

## Expected behavior

插件应该正常更新

## Extension Output

我修改了extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/config.js中的plugin字段为'https://raw.githubusercontent.com/leetcode-tools/leetcode-cli-plugins/master/plugins/$name.js'，
之后用proxy更新，回复到正常状态

## Your Environment

- *os*: archlinux, [majaro distro]
- *extension settings*: default
- *nodejs version*: v14.3.0
- *vscode version*: v1.47.0
- *extension version*: v0.17.0

**Comment by woofhyx** [comment]
默认的配置字段是'https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/$name.js'，上面的报错是我已经修改了plugin地址，但没修改正确的输出。

**Comment by jdneo** [comment]
https://raw.githubusercontent.com/leetcode-tools/leetcode-cli-plugins/master/plugins/xxx.js  并没有这样的文件存在，为什么要这样改呢？

**Comment by culyee** [comment]
@jdneo 我也遇到这个问题了，要怎么解决呢？

**Comment by yihong0618** [comment]
@jdneo 
我之前发现这块更新不了了，这个pr顺便改了。因为之前的路径404了，plugin无法更新。
https://github.com/leetcode-tools/leetcode-cli/pull/43/commits/4a27102bd629f7f3a93cb250752d26efc24da683

**Comment by yihong0618** [comment]
@woofhyx clean your cache see #593
