### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by AndyYuan96** [LeetCode-OpenSource/vscode-leetcode#591]
Hi, I just can't login, it should be related to proxy problem, And I follow the issues related to proxy, doesn't work.
My vscode config:
 "http.proxyAuthorization": null,
"http.proxy": "http://127.0.0.1:12333",
 "http.proxyStrictSSL": false,
"http.proxySupport": "on",

I can connect to extension market, and I also setting http.proxy.
ERROR:
[ERROR] Error: tunneling socket could not be established, cause=Client network socket disconnected before secure TLS connection was established

in develop model, it output:
POST https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery net::ERR_PROXY_CONNECTION_FAILED

**Comment by yihong0618** [comment]
Try to coneect with your smartphone hotspot see if can connect or not ?

**Comment by AndyYuan96** [comment]
> Try to coneect with your smartphone hotspot see if can connect or not ?

..sorry, I use Desktop, not laptop

**Comment by yihong0618** [comment]
> > Try to coneect with your smartphone hotspot see if can connect or not ?
> 
> 
> 
> ..sorry, I use Desktop, not laptop

As I know if you use ss or ssr  which use socks5，the
http proxy is not fit。

**Comment by AndyYuan96** [comment]
> > > Try to coneect with your smartphone hotspot see if can connect or not ?
> > 
> > 
> > ..sorry, I use Desktop, not laptop
> 
> As I know if you use ss or ssr which use socks5，the
> http proxy is not fit。
> Can you use leetcode-cn without proxy?

I can login in leetcode-cli, but can't use leetcode list get question, it return "[ERROR] http error [code=400]
", do you think this is network problem related to company?

**Comment by AndyYuan96** [comment]
> > > Try to coneect with your smartphone hotspot see if can connect or not ?
> > 
> > 
> > ..sorry, I use Desktop, not laptop
> 
> As I know if you use ss or ssr which use socks5，the
> http proxy is not fit。
> Can you use leetcode-cn without proxy?

I use v2ray, and just setting http_proxy, I can google.

**Comment by AndyYuan96** [comment]
give up,  leetcode editor is a extension for clion, just install and login, no error.
