### ISSUE TITLE
fail to install plugin

### ISSUE THREAD

**Issue by wnykuang** [LeetCode-OpenSource/vscode-leetcode#593]
## 🐛 Bug Report

Extension initialization failed. 

## To Reproduce
1. uninstall leetcode-vscode
2. reinstall leetcode-vscode
3. run the plugin, you will see it.
## Expected behavior

leetcode-vscode should be ran smoothly.

## Extension Output

v12.18.2
[WARN] Installing missing plugins, might take a while ...
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/github.js
[ERROR] HTTP Error: 404
[WARN] Installing missing plugins, might take a while ...
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/github.js
[ERROR] HTTP Error: 404
Error: Command "node "/Users/xxxxxxx/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/bin/leetcode",plugin,-i,company" failed with exit code "1".

## Your Environment

- *os*: MacOS 10.15.5
- *extension settings*: 
- *nodejs version*: node-v12.18.2
- *vscode version*: 1.46.1
- *extension version*: 0.17.0

note:
I believe the problem is caused by the 404 from 
https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/github.js

I hope it helps. :D

**Comment by AndyYuan96** [comment]
I meet the similar problem yesterday, the error is 404, but I go through plugins installation, I meet 404 when list questions in leetcode-cli,  it should be related to your vpn or shadowsocks, finally I didn't solve it. Now I use the leetcode extension in clion IDE, 
just login in, nothing to wrong, you can start use.

**Comment by wnykuang** [comment]
> I meet the similar problem yesterday, the error is 404, but I go through plugins installation, I meet 404 when list questions in leetcode-cli, it should be related to your vpn or shadowsocks, finally I didn't solve it. Now I use the leetcode extension in clion IDE,
> just login in, nothing to wrong, you can start use.

meh, I am not using any VPN/ssr.

**Comment by AndyYuan96** [comment]
> > I meet the similar problem yesterday, the error is 404, but I go through plugins installation, I meet 404 when list questions in leetcode-cli, it should be related to your vpn or shadowsocks, finally I didn't solve it. Now I use the leetcode extension in clion IDE,
> > just login in, nothing to wrong, you can start use.
> 
> meh, I am not using any VPN/ssr.

I don't know why, as I'm not familar with js, I don't know how to find reason, so other ide may be a good choice.

**Comment by yihong0618** [comment]
@wnykuang get your point, let me have a check.

**Comment by yihong0618** [comment]
@wnykuang  did you use proxy?

**Comment by wnykuang** [comment]
@yihong0618  nope, I didn't change any settings about the internet.

Could you open the URL?

https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/github.js

**Comment by yihong0618** [comment]
> @yihong0618 nope, I didn't change any settings about the internet.
> 
> Could you open the URL?
> 
> https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/github.js

No, but its not the  404 url problem,  github.js is the third party plugin which would not install usually, I have tried three different  environment but I didn't  locate your problem yet.

**Comment by wnykuang** [comment]
@yihong0618 
interesting.

Do you need any more information?
like some npm call or so?

**Comment by yihong0618** [comment]
> @yihong0618
> interesting.
> 
> Do you need any more information?
> like some npm call or so?

Yes what my guess is you use vscode-leetcode or leetcode-cli before and  installed these third-party plugins maybe you are not notice,  am I right?

**Comment by wnykuang** [comment]
@yihong0618 
I have used leetcode-cli for years until last year I cannot log in anymore.
Do you know how to reset/delete the plugins?

**Comment by yihong0618** [comment]
@wnykuang 
If so, can you make a test that remove the cache, use `rm -rf ~/.lc/`  and try to login again.

**Comment by wnykuang** [comment]
@yihong0618 

after ```rm -rf ~/.lc/ ``` the leetcode-vscode works!

Thank you!

**Comment by yihong0618** [comment]
> @yihong0618
> I have used leetcode-cli for years until last year I cannot log in anymore.
> Do you know how to reset/delete the plugins?

My thinking is that use use third-party  **github.js** and it saves in cache, and this time need to update caused these error.

**Comment by jdneo** [comment]
@yihong0618 @zry656565 Seems that we need a way to make sure users are in a fresh env when they first use the extension. Like store some flags in the extension's global storage.

**Comment by yihong0618** [comment]
> @yihong0618
> 
> after `rm -rf ~/.lc/ ` the leetcode-vscode works!
> 
> Thank you!
My pleasure
@AndyYuan96 can you try this too?

**Comment by yihong0618** [comment]
@jdneo @zry656565 
Can we make a popup on this error handling? Tell the user error hanpens and let user decide  delete the cache or not.
```TypeScript
        for (const plugin of supportedPlugins) {
            try { // Check plugin
                await this.executeCommandEx(this.nodeExecutable, [await this.getLeetCodeBinaryPath(), "plugin", "-e", plugin]);
            } catch (error) { // Download plugin and activate
                // popup
                await this.executeCommandEx(this.nodeExecutable, [await this.getLeetCodeBinaryPath(), "plugin", "-i", plugin]);
            }
        }
```

**Comment by jdneo** [comment]
This is a good way to handle the error. While we also need a way to eliminate those errors at the first stage. For example, in the `activate()`, check if there is a certain flag in the global storage. If not, clean the cache, and leave the flag before the `activate()` finishes.

**Comment by milpita** [comment]
I noticed it failed due to extension not supporting older vscode-1.36 (june 2019). Make sure vscode up to date and try installing again. If problem persists, this can help troubleshoot, download the [vsix ](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/LeetCode/vsextensions/vscode-leetcode/0.17.0/vspackage) and in cmd: `code --install-extension path_to_vsix_file --verbose`.
