### ISSUE TITLE
如何将pick one得到的题目加到favorite中？

### ISSUE THREAD

**Issue by FZ-c** [LeetCode-OpenSource/vscode-leetcode#598]
如题。

**Comment by yihong0618** [comment]
Find id in the editor and then star on the side bar?
![image](https://user-images.githubusercontent.com/15976103/87652025-44151980-c786-11ea-808f-c7a219766189.png)

**Comment by jdneo** [comment]
@yihong0618 This is a valid workaround.

I think this issue is duplicated with #549 

Close it for duplication

**Comment by FZ-c** [comment]
> Find id in the editor and then star on the side bar?
> ![image](https://user-images.githubusercontent.com/15976103/87652025-44151980-c786-11ea-808f-c7a219766189.png)

It may not be convenient, but it works. thank you~
