### ISSUE TITLE
The problem of "identifier unordered_map is undefined" appears in the compiler. What should I do?

### ISSUE THREAD

**Issue by Waiibiwaibi** [LeetCode-OpenSource/vscode-leetcode#603]
## 💬 Questions and Help

When "vector", "map" and other data types appear in the title, vscode tells me that they are not defined. But they can be tested and submitted. But the compiler still told me they were wrong,  and I want to know how to tell the compiler they're not wrong.
![image](https://user-images.githubusercontent.com/40908894/88211164-e4d46f00-cc87-11ea-9f6b-c58c693caa59.png)

**Comment by jdneo** [comment]
This is reported by other extension. i.e. c++ extension, if you installed.

LeetCode so far do not have any intellisense related features. So it's out of our scope.
