### ISSUE TITLE
Can not sign in leetcode-cn.com

### ISSUE THREAD

**Issue by Aaronself** [LeetCode-OpenSource/vscode-leetcode#605]
Environment
- *os*: Win10

when I find the plugin leetcode in vscode, i download it and find can't sigin in. I tried login with github, accounts and cookies but it dose not work.

Then I find the issue`#478` and download the `leetcode-cli version 2.7.0` and i tried login with github, accounts and cookies but still doesn't work.

when I login with github.  it shows
```
[ERROR] Login failed. Please make sure the credential is correct.
```

and when I login with leetcode account.  it shows
```
[ERROR] invalid password?
```

and I also tried login with cookie, it show something different.
```
[WARN] Failed to retrieve user favorites: [object Object]
C:\Users\XXX\AppData\Roaming\npm\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:525
        user.paid = _user.isCurrentUserPremium;
                          ^

TypeError: Cannot read property 'isCurrentUserPremium' of null
    at C:\Users\XXX\AppData\Roaming\npm\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:525:27
    at Request._callback (C:\Users\XXX\AppData\Roaming\npm\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:431:12)
    at Request.self.callback (C:\Users\XXX\AppData\Roaming\npm\node_modules\vsc-leetcode-cli\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\XXX\AppData\Roaming\npm\node_modules\vsc-leetcode-cli\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\XXX\AppData\Roaming\npm\node_modules\vsc-leetcode-cli\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
```
actually, i hidden account information and use the `XXX` instead。

So, how can i  solve this problem, thank you very much.

**Comment by yihong0618** [comment]
Did you link your account to github？

**Comment by Aaronself** [comment]
may i asked how to link to github?

**Comment by yihong0618** [comment]
> may i asked how to link to github?

Login leetcode, in this url https://leetcode.com/profile/account/

You can click the arrow button to login GitHub, then try login in vscode-leetcode again.
![image](https://user-images.githubusercontent.com/15976103/88300767-6d114d80-cd36-11ea-8c35-aa3fccbd616f.png)

**Comment by Aaronself** [comment]
actually i already link the leetcode to github.

But i use the `leetcode-cn.com`, can it still work?

**Comment by yihong0618** [comment]
> actually i already link the leetcode to github.
> 
> But i use the `leetcode-cn.com`, can it still work?

@Aaronself  for leetcode.cn I think the origin accout can login.
1. please make sure your node version is more than 10+
2. please make sure you have switched to leetcode.cn endpoint

**Comment by Aaronself** [comment]
`node version 12.18.2`
may I ask how to change to `leetcode.cn`

**Comment by yihong0618** [comment]
![image](https://user-images.githubusercontent.com/15976103/88367431-4c8cd600-cdbe-11ea-87a5-03ef23310e90.png)

**Comment by Aaronself** [comment]
ok, thank you. I find it is strange that the UI is different from yesterday. Yesterday i can only find the button sign in. And today i find other buttons and sign in successfully. thank you very much.
