### ISSUE TITLE
Unable to input string in the command palette as test case with C++

### ISSUE THREAD

**Issue by BillChen2K** [LeetCode-OpenSource/vscode-leetcode#608]
## 🐛 Bug Report

Unable to input string in the command palette as test case. The quotes won't be handled properly.

For instance for the problem [5](https://leetcode-cn.com/problems/longest-palindromic-substring/), no matter I input `"abba"` or `abba` as the input string, I get the following errors:

```
terminate called after throwing an instance of 'std::logic_error'
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
```

While in the online website, the string can be handled properly with quotes.

## To Reproduce

Input string-type test case in the command palette.

## Expected behavior

The input LeetCode get should have quotes around my input so that it can be seen as a valid string.

## Extension Output

```
- Waiting for judge result
- Waiting for judge result
- Waiting for judge result
- Waiting for judge result
- Waiting for judge result
- Waiting for judge result
- Waiting for judge result
- Waiting for judge result
  ✘ Runtime Error
  ✘ Error: terminate called after throwing an instance of 'std::logic_error'
  ✘ Error: terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
  ✘ Your Input: abba
  ✘ Stdout: 
```

## Your Environment

- *os*: macOS 10.14.6
- *extension settings*: (All default)
- *nodejs version*: 14.5.0
- *vscode version*: 1.47.3
- *extension version*: 0.17.0

**Comment by yihong0618** [comment]
@BillChen2K
Did you use wsl?
Try to use `'"abba"'` instead.

**Comment by BillChen2K** [comment]
> @BillChen2K
> In this case seems you need to add another quotes,
> like ""abba""

Thanks, it worked
