### ISSUE TITLE
Session expired

### ISSUE THREAD

**Issue by Rosonlee** [LeetCode-OpenSource/vscode-leetcode#609]
When I log in with web ,the account in vscode says sessions expired.
It just happens today, that means I can't log in with vs and web at the same time?
I used to submit with vs and write solutions through web.
It always works until today

**Comment by Dreace** [comment]
The same problem, even using cookie to log in will make web log out.

**Comment by yihong0618** [comment]
Did you use leetcode or leetcode-cn? I didn't have this problem for leetcode both cookie login or third party login.

**Comment by Rosonlee** [comment]
> Did you use leetcode or leetcode-cn? I didn't have this problem for leetcode both cookie login or third party login.

Leetcode-cn, It just happened today.

**Comment by yihong0618** [comment]
Yes, I checked.Leetcode-cn change the policy.

**Comment by yihong0618** [comment]
I think there is no better solution for now.
Old leetcode-cli use share cookie way when they have this problem https://github.com/skygragon/leetcode-cli-plugins/blob/master/plugins/cookie.chrome.js, but I don't think it is a good way,

**Comment by Rosonlee** [comment]
> Yes, I checked.Leetcode-cn change the policy.

Ok, hope to fix it laterly, thank you

**Comment by Miloas** [comment]
fixed

**Comment by Rosonlee** [comment]
It happens again

**Comment by Rosonlee** [comment]
> fixed

It happens again
