### ISSUE TITLE
Cannot install from extension and marketplace VS code 1.41.1

### ISSUE THREAD

**Issue by Skye227-coding** [LeetCode-OpenSource/vscode-leetcode#616]
## install from extension
error message:Failed to install 'leetcode.vscode-leetcode'.

## install from marketplace
I just download it from market place and try to open it within vs code. A error message pops up like below:
Unable to install extension 'leetcode.vscode-leetcode' as it is not compatible with VS Code '1.41.1'.

**Comment by jdneo** [comment]
As the message says please upgrade your vs code version to latest.
