### ISSUE TITLE
无法登录leetcode-cn

### ISSUE THREAD

**Issue by kerryChen95** [LeetCode-OpenSource/vscode-leetcode#624]
## To Reproduce

1. 切换到leetcode-cn
![image](https://user-images.githubusercontent.com/1589388/92593670-18209b00-f2d4-11ea-985c-6d5ea2c6e15e.png)
2. 尝试用leetcode账号登录
3. 尝试用github账号登录
![image](https://user-images.githubusercontent.com/1589388/92593705-21116c80-f2d4-11ea-94d8-d4ea6774fd40.png)

## Expected behavior

期望登录成功

## Extension Output

都提示登录失败

```
v14.3.0
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✘     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✘     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
(node:42708) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✘     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
(node:42709) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
(node:42710) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
(node:42712) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] You are not login yet?
(node:42715) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
login: (node:42717) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: - Signing in leetcode-cn.com
[ERROR] invalid password?
login: (node:42734) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: [ERROR] invalid cookie?
/Users/kerry95/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:569
    user.sessionId = cookieData.sessionId;
                                ^

TypeError: Cannot read property 'sessionId' of undefined
    at Request._callback (/Users/kerry95/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:569:33)
    at Request.self.callback (/Users/kerry95/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/Users/kerry95/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/Users/kerry95/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

## Your Environment

- *os*: macOS Catalina 10.15.6
- *extension settings*: 安装后的默认设置
- *nodejs version*: v14.3.0
- *vscode version*: 1.48.2
- *extension version*: 0.17.0

**Comment by yihong0618** [comment]
在leetcode-cn注册，用leetcode-cn账号登陆试一下？目前两个账号是不通用的，我一会试验一下。

**Comment by kerryChen95** [comment]
> 在leetcode-cn注册，用leetcode-cn账号登陆试一下？目前两个账号是不通用的，我一会试验一下。

leetcode-cn能登录进去

**Comment by yihong0618** [comment]
@kerryChen95 you can close this.

**Comment by kerryChen95** [comment]
我是说在 leetcode-cn 网站能登录进去，但是在VS Code LeetCode插件中还是有问题的。

刚才找到原因并临时解决了！

如下截图，`vsc-leetcode-cli` v2.7.0 中的代码有问题，主要有：
1. 通过cookie来登录时，`cookieLogin` 函数中调用的是 `parseCookie(user.cookie, cb)` ，但 `parseCookie` 函数中其实不支持第2个参数是 `cb`。
2. 通过github登录时，`parseCookie` 函数中总是拿不到 `reCsrfResult` ，至于原因，我看代码是从 `cookie` 或 `body` 中获取，我将两者打印出来，按 `parseCookie` 函数中的正则都获取不到，可能需要换别的方式获取。

问题2可以临时解决，从leetcode-cn网站cookie中手动获取名为 `csrftoken` 的cookie值，写死在`parseCookie` 函数中返回即可。
![image](https://user-images.githubusercontent.com/1589388/92597451-fcb88e80-f2d9-11ea-8dd8-85b76d7009d4.png)
![image](https://user-images.githubusercontent.com/1589388/92597182-9b90bb00-f2d9-11ea-8e19-81f228c39b54.png)

**Comment by kerryChen95** [comment]
`vsc-leetcode-cli` v2.7.0 有问题，建议先降级使用，并反馈给 `vsc-leetcode-cli`

**Comment by yihong0618** [comment]
@kerryChen95 感谢反馈，我知道这个问题，leetcode-cn更改了拿csrf的方式，目前我还没找到好的方法解决。针对leetcode-cn请用原始账号登陆目前不支持第三方。see #619 
再次感谢～

**Comment by yihong0618** [comment]
@kerryChen95 目前两套系统有点混乱，leetcode-cn不支持第三方，leetcode只支持第三方。。。

**Comment by kerryChen95** [comment]
> @kerryChen95 感谢反馈，我知道这个问题，leetcode-cn更改了拿csrf的方式，目前我还没找到好的方法解决。针对leetcode-cn请用原始账号登陆目前不支持第三方。see #619
> 再次感谢～

使用leetcode-cn账号登录也走不通，我现在找不到登出插件的入口，复现不了

**Comment by yihong0618** [comment]
> > @kerryChen95 感谢反馈，我知道这个问题，leetcode-cn更改了拿csrf的方式，目前我还没找到好的方法解决。针对leetcode-cn请用原始账号登陆目前不支持第三方。see #619
> > 再次感谢～
> 
> 使用leetcode-cn账号登录也走不通，我现在找不到登出插件的入口，复现不了

我的账号没问题，刚测试了下。用了mac和win都试了。

**Comment by kerryChen95** [comment]
> > > @kerryChen95 感谢反馈，我知道这个问题，leetcode-cn更改了拿csrf的方式，目前我还没找到好的方法解决。针对leetcode-cn请用原始账号登陆目前不支持第三方。see #619
> > > 再次感谢～
> > 
> > 
> > 使用leetcode-cn账号登录也走不通，我现在找不到登出插件的入口，复现不了
> 
> 我的账号没问题，刚测试了下。用了mac和win都试了。
> ![image](https://user-images.githubusercontent.com/15976103/92600092-aea58a00-f2dd-11ea-967e-91c1c260afc8.png)

这是用leetcode-cn账号登录的报错信息

```
v14.3.0
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
(node:45685) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
(node:45686) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
(node:45687) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
(node:45688) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] You are not login yet?
(node:45689) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
login: (node:45690) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: - Signing in leetcode-cn.com
[ERROR] invalid password?
```

**Comment by yihong0618** [comment]
错误显示的是密码不对？

**Comment by kerryChen95** [comment]
密码应该没错，试了挺多次了，在网站也登录进去了。

代码里判断了是否302跳转，是不是没支持跳转？
![image](https://user-images.githubusercontent.com/1589388/92601020-dcd79980-f2de-11ea-885f-8a7aac4d92a0.png)

**Comment by kerryChen95** [comment]
刚才又试了一下，在使用leetcode-cn账号登录时确实是密码输错了，希望插件在输入密码时支持cmd+v粘贴，目前只能手动输入或右键粘贴。

不过走github或cookie登录的问题还是存在的，希望我提供的信息有助于解决，谢谢～

**Comment by yihong0618** [comment]
> 刚才又试了一下，在使用leetcode-cn账号登录时确实是密码输错了，希望插件在输入密码时支持cmd+v粘贴，目前只能手动输入或右键粘贴。
> 
> 不过走github或cookie登录的问题还是存在的，希望我提供的信息有助于解决，谢谢～

你可以尝试下～国内账号改了机制，之前从body可以拿到，现在csrf token貌似不太好拿。不过国内原始账号暂时可以登陆，我再想想办法。

**Comment by BUGyyc** [comment]
遇到了同样的问题

**Comment by yangjocy** [comment]
遇到了同样的问题，疑似因 parseCookie 不支持 cb 入参导致。 @yihong0618 
`login: pass:  Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   √     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
[ERROR] You are not login yet?
login: login: cookie: login: pass: login: cookie: c:\Users\xingxiu\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:554
    return cb('invalid cookie?');
           ^

TypeError: cb is not a function
    at parseCookie (c:\Users\xingxiu\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:554:12)
    at Plugin.plugin.cookieLogin (c:\Users\xingxiu\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:577:22)
    at c:\Users\xingxiu\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\commands\user.js:119:12
    at c:\Users\xingxiu\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:336:32
    at c:\Users\xingxiu\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\utile\node_modules\async\lib\async.js:154:25
    at assembler (c:\Users\xingxiu\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:333:9)
    at c:\Users\xingxiu\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:342:32
    at c:\Users\xingxiu\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:625:5
    at Interface.onLine (c:\Users\xingxiu\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\read\lib\read.js:111:5)
    at Interface.emit (events.js:210:5)
login: cookie: c:\Users\xingxiu\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:554
    return cb('invalid cookie?');`

**Comment by yihong0618** [comment]
> 遇到了同样的问题，疑似因 parseCookie 不支持 cb 入参导致。 @yihong0618
> 
> ## `login: pass: Active Name Version Desc
> √ solution.discuss 2019.02.03 Plugin to fetch most voted solution in discussions.
> √ company 2017.12.18 Plugin to query by company for free user.
> √ cache default Plugin to provide local cache.
> √ retry default Plugin to retry last failed request if autologin.enable is on.
> √ leetcode.cn 2018.11.25 Plugin to talk with leetcode-cn APIs.
> √ leetcode default Plugin to talk with leetcode APIs.
> [ERROR] You are not login yet?
> login: login: cookie: login: pass: login: cookie: c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:554
> return cb('invalid cookie?');
> ^
> 
> TypeError: cb is not a function
> at parseCookie (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:554:12)
> at Plugin.plugin.cookieLogin (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:577:22)
> at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\commands\user.js:119:12
> at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:336:32
> at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\utile\node_modules\async\lib\async.js:154:25
> at assembler (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:333:9)
> at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:342:32
> at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:625:5
> at Interface.onLine (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\read\lib\read.js:111:5)
> at Interface.emit (events.js:210:5)
> login: cookie: c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:554
> return cb('invalid cookie?');`

用原始账号登陆，目前第三方不好用

**Comment by yangjocy** [comment]
> > 遇到了同样的问题，疑似因 parseCookie 不支持 cb 入参导致。 @yihong0618
> > ## `login: pass: Active Name Version Desc
> > √ solution.discuss 2019.02.03 Plugin to fetch most voted solution in discussions.
> > √ company 2017.12.18 Plugin to query by company for free user.
> > √ cache default Plugin to provide local cache.
> > √ retry default Plugin to retry last failed request if autologin.enable is on.
> > √ leetcode.cn 2018.11.25 Plugin to talk with leetcode-cn APIs.
> > √ leetcode default Plugin to talk with leetcode APIs.
> > [ERROR] You are not login yet?
> > login: login: cookie: login: pass: login: cookie: c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:554
> > return cb('invalid cookie?');
> > ^
> > TypeError: cb is not a function
> > at parseCookie (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:554:12)
> > at Plugin.plugin.cookieLogin (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:577:22)
> > at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\commands\user.js:119:12
> > at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:336:32
> > at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\utile\node_modules\async\lib\async.js:154:25
> > at assembler (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:333:9)
> > at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:342:32
> > at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:625:5
> > at Interface.onLine (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\read\lib\read.js:111:5)
> > at Interface.emit (events.js:210:5)
> > login: cookie: c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:554
> > return cb('invalid cookie?');`
> 
> 用原始账号登陆，目前第三方不好用

是用 cookie 登录的

**Comment by yihong0618** [comment]
> > > 遇到了同样的问题，疑似因 parseCookie 不支持 cb 入参导致。 @yihong0618
> > > ## `login: pass: Active Name Version Desc
> > > √ solution.discuss 2019.02.03 Plugin to fetch most voted solution in discussions.
> > > √ company 2017.12.18 Plugin to query by company for free user.
> > > √ cache default Plugin to provide local cache.
> > > √ retry default Plugin to retry last failed request if autologin.enable is on.
> > > √ leetcode.cn 2018.11.25 Plugin to talk with leetcode-cn APIs.
> > > √ leetcode default Plugin to talk with leetcode APIs.
> > > [ERROR] You are not login yet?
> > > login: login: cookie: login: pass: login: cookie: c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:554
> > > return cb('invalid cookie?');
> > > ^
> > > TypeError: cb is not a function
> > > at parseCookie (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:554:12)
> > > at Plugin.plugin.cookieLogin (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:577:22)
> > > at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\commands\user.js:119:12
> > > at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:336:32
> > > at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\utile\node_modules\async\lib\async.js:154:25
> > > at assembler (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:333:9)
> > > at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:342:32
> > > at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:625:5
> > > at Interface.onLine (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\read\lib\read.js:111:5)
> > > at Interface.emit (events.js:210:5)
> > > login: cookie: c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:554
> > > return cb('invalid cookie?');`
> > 
> > 
> > 用原始账号登陆，目前第三方不好用
> 
> 是用 cookie 登录的

cn 不需要cookie，直接登陆就行。只有leetcode.com才需要

**Comment by Thvrudorv** [comment]
> > 遇到了同样的问题，疑似因 parseCookie 不支持 cb 入参导致。 @yihong0618
> > ## `login: pass: Active Name Version Desc
> > √ solution.discuss 2019.02.03 Plugin to fetch most voted solution in discussions.
> > √ company 2017.12.18 Plugin to query by company for free user.
> > √ cache default Plugin to provide local cache.
> > √ retry default Plugin to retry last failed request if autologin.enable is on.
> > √ leetcode.cn 2018.11.25 Plugin to talk with leetcode-cn APIs.
> > √ leetcode default Plugin to talk with leetcode APIs.
> > [ERROR] You are not login yet?
> > login: login: cookie: login: pass: login: cookie: c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:554
> > return cb('invalid cookie?');
> > ^
> > TypeError: cb is not a function
> > at parseCookie (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:554:12)
> > at Plugin.plugin.cookieLogin (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:577:22)
> > at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\commands\user.js:119:12
> > at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:336:32
> > at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\utile\node_modules\async\lib\async.js:154:25
> > at assembler (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:333:9)
> > at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:342:32
> > at c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\prompt\lib\prompt.js:625:5
> > at Interface.onLine (c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\read\lib\read.js:111:5)
> > at Interface.emit (events.js:210:5)
> > login: cookie: c:\Users\xingxiu.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:554
> > return cb('invalid cookie?');`
> 
> 用原始账号登陆，目前第三方不好用

我使用的是美国站账户同步到leetcode-cn使用，在选择中文站的前提下，输入原始账户也没办法登录

**Comment by Leconomy** [comment]
我也遇到同样的问题，登陆时输入邮箱和密码，总是报 invalid password 。我确定我的密码没有输入错误

**Comment by Leconomy** [comment]
> 我也遇到同样的问题，登陆时输入邮箱和密码，总是报 invalid password 。我确定我的密码没有输入错误

我解决了，需要修改 LeetCode：Endpoint为leetcode-cn，然后重启vscode，再登陆，成功

**Comment by zmwxiaoming** [comment]
> > 我也遇到同样的问题，登陆时输入邮箱和密码，总是报 invalid password 。我确定我的密码没有输入错误
> 
> 我解决了，需要修改 LeetCode：Endpoint为leetcode-cn，然后重启vscode，再登陆，成功

谢谢大佬,确实解决了问题

**Comment by blxie** [comment]
v14.16.0
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   √     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
(node:4032) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   √     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
(node:12488) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   √     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
(node:916) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   √     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
(node:7532) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] You are not login yet?
(node:6068) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
login: (node:12492) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: - Signing in leetcode-cn.com
[ERROR] invalid password?

**Comment by blxie** [comment]
原因：leetcode-cn的用户名是手机或者邮箱，不能用昵称登录，我就是这个原因，在官网退出登陆后发现用昵称登录不了

![image](https://user-images.githubusercontent.com/43612290/111495637-89a53e80-877a-11eb-9d32-cdb271901299.png)
![image](https://user-images.githubusercontent.com/43612290/111495862-bb1e0a00-877a-11eb-8d80-c97c4057966d.png)

换成邮箱或者手机号后：
![image](https://user-images.githubusercontent.com/43612290/111496017-ddb02300-877a-11eb-923c-2cccc691484c.png)

登录成功

**Comment by Wu-yikun** [comment]
> 我是说在 leetcode-cn 网站能登录进去，但是在VS Code LeetCode插件中还是有问题的。
> 
> 刚才找到原因并临时解决了！
> 
> 如下截图，`vsc-leetcode-cli` v2.7.0 中的 `vsc-leetcode-cli/lib/plugins/leetcode.js` 代码有问题，主要有：
> 
> 1. 通过cookie来登录时，`cookieLogin` 函数中调用的是 `parseCookie(user.cookie, cb)` ，但 `parseCookie` 函数中其实不支持第2个参数是 `cb`。
> 2. 通过github登录时，`parseCookie` 函数中总是拿不到 `reCsrfResult` ，至于原因，似乎国内网站也应该是从 `cookie` 而不是从 `body` 中拿 `csrftoken`，对应截图中的552行。
> 
> 问题2我临时解决了一下，从leetcode-cn网站cookie中手动获取名为 `csrftoken` 的cookie值，写死在`parseCookie` 函数中返回即可。 ![image](https://user-images.githubusercontent.com/1589388/92597451-fcb88e80-f2d9-11ea-8dd8-85b76d7009d4.png) ![image](https://user-images.githubusercontent.com/1589388/92597182-9b90bb00-f2d9-11ea-8e19-81f228c39b54.png)

我尝试多遍依旧如此[ERROR] Login failed. Please make sure the credential is correct，请问还有其余的解决方法吗

**Comment by mingoahead** [comment]
账户密码方式，登陆leetcode-cn, 提示invalid password，确认密码没有错误，有人报同样错误么？
<img width="789" alt="image" src="https://user-images.githubusercontent.com/8349548/179711559-44e378c0-7260-49be-9991-e6712801a6ec.png">

**Comment by shixin398** [comment]
> 确认密码没有错误，有人报同样错误

+1，do you fix it？

**Comment by huidaxian** [comment]
mac 设置了中国区，还是登录不了

**Comment by Bang0518** [comment]
> 账户密码方式，登陆leetcode-cn, 提示invalid password，确认密码没有错误，有人报同样错误么？ <img alt="image" width="789" src="https://user-images.githubusercontent.com/8349548/179711559-44e378c0-7260-49be-9991-e6712801a6ec.png">

我报这个错，你解决了吗？

**Comment by Bang0518** [comment]
> mac 设置了中国区，还是登录不了

请问你解决了吗？我也有同样问题
