### ISSUE TITLE
已有会员的账号无法显示加锁的问题？

### ISSUE THREAD

**Issue by iElric** [LeetCode-OpenSource/vscode-leetcode#629]
买了leetcode的会员，但是我发现在插件中还是看不到上锁的问题，我试了登出重登入还是不行。

**Comment by pintaigao** [comment]
在VSCode设置-->Leetcode区域那里有一个Show locked problems选项，你看看是不是没有打勾？
![image](https://user-images.githubusercontent.com/25647391/93551473-f3fc3400-f93b-11ea-9fd7-3aa8746ec99e.png)

**Comment by iElric** [comment]
看到了，谢谢！
