### ISSUE TITLE
No identifier is defined

### ISSUE THREAD

**Issue by QiuXinYan** [LeetCode-OpenSource/vscode-leetcode#630]
## 💬 Questions and Help

Please outline the questions.
Under the LeetCode plug-in, I can debug and submit, but the vector is shown as an undefined identifier.

**Comment by QiuXinYan** [comment]
![sp200918_114845](https://user-images.githubusercontent.com/50079348/93553166-ec24aa00-f9a4-11ea-823b-bdffcfd4a1d2.png)
just like this

**Comment by jdneo** [comment]
The LeetCode extension does not provide any language intellisense related features. Please check if you have installed any language extensions (for example, C++ extension).
