### ISSUE TITLE
Can't find submit or test button

### ISSUE THREAD

**Issue by heatherwang39** [LeetCode-OpenSource/vscode-leetcode#631]
I cannot find the submit or test button. I installed the leetcode plugin in vscode. 
The "shortcut" setting have "submit" and "test". But I can't find them after I finish the code. 

 
![4108d933efcaadef5f263d9be4e1676](https://user-images.githubusercontent.com/55209507/93965294-c80ff280-fd2f-11ea-9397-5bd42943cc83.png)

**Comment by JackFlyL** [comment]
me too

**Comment by jdneo** [comment]
Please do not remove the line `@lc code=....`

The extension is using it to find if current file is a leetcode solution file or not.

**Comment by Dylan-zhu** [comment]
@jdneo I open a new question, but the submit and test buttons can't be found. I have re-installed leetcode and vs code on my side.
![image](https://user-images.githubusercontent.com/29833057/103338340-0c422a00-4ab9-11eb-92fd-d1ee99271cac.png)

**Comment by Yeezy7** [comment]
I also encountered this problem, thank you for your method.

> I open a new question, but the submit and test buttons can't be found. I have re-installed leetcode and vs code on my side.我打开了一个新问题，但找不到 submit （提交） 和 test （测试） 按钮。我已经在我这边重新安装了 leetcode 和 vs code。
> 
> ### Solved:
> "editor.codeLens" must be true.“editor.codeLens” 必须为 true。 ![image](https://user-images.githubusercontent.com/29833057/103338773-714a4f80-4aba-11eb-9e8a-a143ab99fe52.png)
