### ISSUE TITLE
Editor Shortcuts 添加 add to favorite list 的快捷方式

### ISSUE THREAD

**Issue by LogicJake** [LeetCode-OpenSource/vscode-leetcode#634]
## 🚀 Feature Proposal

Editor Shortcuts 添加 add to favorite list 的快捷方式

## Motivation

自己搜索题，如果打算将这道题添加到 favorite 列表，还需要从all列表下一个一个找过去，比较费事。
## Contribution

Please describe the solution if you'd like to submit a PR.

**Comment by jdneo** [comment]
It's supported now, use `leetcode.editor.shortcuts` and add `star` to the setting array.
