### ISSUE TITLE
Add problem description language switch

### ISSUE THREAD

**Issue by tishion** [LeetCode-OpenSource/vscode-leetcode#636]
## 🚀 Feature Proposal

We know that in leetcode-cn website we can select the problems description language (Chinese/English). Can we have this feature in this extension?

## Motivation

Most people would like to read the problem in English. We sure could switch the endpoint to leetcode-us, but what if I have bought the premium in leetcode-cn?

## Contribution

I have no idea, maybe we can just add one parameter to indicate the desired language in the api request?

**Comment by jdneo** [comment]
Fixed by #690
