### ISSUE TITLE
leetcode.editor.shortcuts 参数问题

### ISSUE THREAD

**Issue by InVinCiblezz** [LeetCode-OpenSource/vscode-leetcode#653]
`leetcode.editor.shortcuts | Specify the customized shorcuts in editors. Supported values are: submit, test, star, solution and description. | ["submit, test"]`

我有2个问题，
1. 这里的default value 应该是["submit", "test"]吗？
2. 似乎并不支持star参数

**Comment by jdneo** [comment]
> 这里的default value 应该是["submit", "test"]吗？
是的

> 似乎并不支持star参数
star已经支持
