### ISSUE TITLE
是否考虑加入一键选择每日一题功能

### ISSUE THREAD

**Issue by cncsl** [LeetCode-OpenSource/vscode-leetcode#657]
## 🚀 Feature Proposal

与点击 Pick One 相同，一键选择每日一题

## Motivation

自从 LeetCode-Cn 上线每日一题之后，每次刷题都是先去网页搜索题目、随后在 vscode-leetcode 中使用搜索功能搜索题号，能否在 Pick One 的菜单项下方再加一项用于一键打开每日一题。

## Contribution

看了一下全球站没有每日一题，这个菜单项需要先判断选中的站点

**Comment by kagaya85** [comment]
+1
同需要每日一题

**Comment by supperchong** [comment]
可以使用插件[algorithm](https://marketplace.visualstudio.com/items?itemName=supperchong.algorithm),包含每日一题和周赛
![image](https://user-images.githubusercontent.com/26317926/122513096-8309ba00-d03c-11eb-9178-3a0fa82ac259.png)

![image](https://user-images.githubusercontent.com/26317926/122513030-61103780-d03c-11eb-9225-cc286dfe2167.png)
