### ISSUE TITLE
能不能增加个 题目中英文显示啊 。 

### ISSUE THREAD

**Issue by qinXpeng** [LeetCode-OpenSource/vscode-leetcode#661]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

Please outline the motivation for the proposal.

## Contribution

Please describe the solution if you'd like to submit a PR.

**Comment by fmy1993** [comment]
+1

**Comment by ChenCyl** [comment]
+1

**Comment by fx109138** [comment]
+1

**Comment by jdneo** [comment]
fixed by #690
