### ISSUE TITLE
Auto-indent with loading new question

### ISSUE THREAD

**Issue by robbyki** [LeetCode-OpenSource/vscode-leetcode#668]
## 💬 Questions and Help

I'm not understanding where to configure or change the default behavior currently where loading a new question in vscode uses 4 spaces for auto-indenting. Is that configurable somewhere? When I create my own new file in my workspace it uses my settings for 2 spaces which is what I want to use when working on an lc question in my editor.

**Comment by TTTPOB** [comment]
definitely need this too
