### ISSUE TITLE
Hope to add the English description for leetcode-cn

### ISSUE THREAD

**Issue by CausingBrick** [LeetCode-OpenSource/vscode-leetcode#672]
## 🚀 Feature Proposal

Hope to add the English description for leetcode-cn, current can only support Chinese description 

## Motivation

I wanna look up English description in leetcode-cn, the web can do that but it‘s absent in vscode-leetcode

**Comment by CausingBrick** [comment]
I think this issue #661  also means the same.

**Comment by jdneo** [comment]
dup with #661
