### ISSUE TITLE
leetcode-cn无法登陆

### ISSUE THREAD

**Issue by jieboom** [LeetCode-OpenSource/vscode-leetcode#700]
## 🐛 Bug Report

无法登录 

## To Reproduce

1. submit时提示session过期, 建议重新登陆
2. 重新登陆所有方式都没有用, enter键入后没有任何toast

## Your Environment

- *os*: win10 1909
- *extension settings*: default
- *nodejs version*:v14.15.4
- *vscode version*: v1.55.2
- *extension version*:v0.17.0

**Comment by qinh** [comment]
node:v12.13.0
vscode:1.56.0
os:mac

没有设置Proxy

[ERROR] Error: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.31.65:80 - Local (192.168.255.10:53083)
为什么会请求：0.0.31.65

**Comment by markexin** [comment]
> ## 🐛 Bug Report
> 无法登录
> 
> ## To Reproduce
> 1. submit时提示session过期, 建议重新登陆
> 2. 重新登陆所有方式都没有用, enter键入后没有任何toast
> 
> ## Your Environment
> * _os_: win10 1909
> * _extension settings_: default
> * _nodejs version_:v14.15.4
> * _vscode version_: v1.55.2
> * _extension version_:v0.17.0

解决方案：
1. 访问本地： ~/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js
2. 将此行代码注释：
![image](https://user-images.githubusercontent.com/18322323/118752337-7b1bf600-b895-11eb-80a3-b331e3282187.png)
3. sessionId sessionCSRF 从力扣官网查找并切写死：LEETCODE_SESSION   csrftoken
4. 重新走下登录，选择cookie登录。即可完成登录~~~

**Comment by labuladong** [comment]
这样写死其实不好，如果 cookie 过期了，还要重新改代码，很麻烦。估计以前中国区的 cookie 格式有些特殊，所以做了特殊处理。现在我看两个区的 cookie 格式是一样的，所以不需要对国内区做特殊处理了，因此，解决这个问题的方法是把下面这行代码：

```javascript
const isCN = config.app === 'leetcode.cn';
```

改为：

```javascript
  const isCN = false;
```

**Comment by yihong0618** [comment]
> 这样写死其实不好，如果 cookie 过期了，还要重新改代码，很麻烦。估计以前中国区的 cookie 格式有些特殊，所以做了特殊处理。现在我看两个区的 cookie 格式是一样的，所以不需要对国内区做特殊处理了，因此，解决这个问题的方法是把下面这行代码：
> 
> ```js
> const isCN = config.app === 'leetcode.cn';
> ```
> 
> 改为：
> 
> ```js
>   const isCN = false;
> ```

是的，这块是我写的，leetcode-cn 目前格式一致了。 pr 已经在上游项目 merge 了，但目前还没发布，可以手动改 leetcode-cli 的版本，然后执行。

**Comment by yihong0618** [comment]
可以看最新的 coomit 和 pr

**Comment by labuladong** [comment]
原来是这样，辛苦大佬 @yihong0618

**Comment by jdneo** [comment]
@yihong0618 是说leetcode-cli吗？pr有链接吗？

**Comment by yihong0618** [comment]
不是啊，是你那个上游项目，之前 merge 那个

**Comment by jdneo** [comment]
ok 了解。那现在应该已经发布了 Thanks!

**Comment by jdneo** [comment]
Closing since it should have been fixed. Thanks for @yihong0618's help.

Feel free to leave comment when you have more questions.
