### ISSUE TITLE
filename language in filepath

### ISSUE THREAD

**Issue by rsonghao** [LeetCode-OpenSource/vscode-leetcode#707]
## 💬 Questions and Help

When I use Leetcode-cn, I try to save the file, but I got the filename using Chinese, not English. How can save the file that name is used English?

**Comment by jdneo** [comment]
You can use the setting `leetcode.useEndpointTranslation` to switch to English.

**Comment by rsonghao** [comment]
> You can use the setting `leetcode.useEndpointTranslation` to switch to English.

Thanks. Next time I will search relative question first.

**Comment by jdneo** [comment]
You are welcome
