### ISSUE TITLE
Error: ENOENT: no such file or directory, mkdir '\\?' Please open the output channel for details.

### ISSUE THREAD

**Issue by wangzhankun** [LeetCode-OpenSource/vscode-leetcode#742]
## 💬 Questions and Help
OS: WINDOWS11
node: 14.16.1

I can login to leetcode-cn.com and fetch the problem successfully. But when I click code now, I get the following error message:
```sh
Error: ENOENT: no such file or directory, mkdir '\\?' Please open the output channel for details.
```
And the warning in the `Output` of vscode is :
```sh
(node:58920) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by Cugtyt** [comment]
same issue

**Comment by Cugtyt** [comment]
@wangzhankun have you solved this issue?

**Comment by GzhiYi** [comment]
same issue.
```
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.3.0
```

**Comment by GzhiYi** [comment]
Setting Workspace Folder to a exist path helps.

**Comment by wangzhankun** [comment]
Please set the correct path in the settings.
![image](https://user-images.githubusercontent.com/35724924/171586814-f068e939-2349-45a6-bde6-07b0f74ad1c9.png)
If you want to open another folder, please change the settings also.

**Comment by kejianfeng** [comment]
@wangzhankun thanks
