### ISSUE TITLE
I can not open the vscode-Leetcode after updating win11

### ISSUE THREAD

**Issue by Chiichen** [LeetCode-OpenSource/vscode-leetcode#758]
## 🐛 Bug Report

When I open vscode-Leetcode after updating the latest win11 version in 2021/11/30, I meet an error

## To Reproduce

Just update the version of Windows 11

## Extension Output

v16.13.0
[ERROR] Plugin not found!
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/company.js
(node:16136) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] Error: read ECONNRESET
Error: Command "node "c:\Users\Chi\.vscode\extensions\leetcode.vscode-leetcode-0.18.0\node_modules\vsc-leetcode-cli\bin\leetcode",plugin,-i,company" failed with exit code "1".

## Your Environment

- *os*: Windows11
- *extension settings*:{
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
    "python.pythonPath": "C:\\Users\\Chi\\AppData\\Local\\Programs\\Python\\Python39\\python.exe",
    "files.autoSave": "afterDelay",
    "java.home":"D:\\JDK",
    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "left"
    },
    "python.defaultInterpreterPath": "C:\\Users\\Chi\\AppData\\Local\\Programs\\Python\\Python39\\python.exe",
    "C_Cpp.updateChannel": "Insiders",
    "leetcode.nodepath": "D:\\Node.js\\node.exe",
    "leetcode.endpoint": "leetcode-cn",
    "leetcode.workspaceFolder": "D:\\my repo\\SummerDay\\CPP\\leetcode",
    "githubIssues.queries": [
        {
            "label": "My Issues",
            "query": "default"
        },
        {
            "label": "Created Issues",
            "query": "author:${user} state:open repo:${owner}/${repository} sort:created-desc"
        }
    ],
    "leetcode.defaultLanguage": "cpp",
    "leetcode.hint.configWebviewMarkdown": false,
    "leetcode.hint.commentDescription": false,
    "cmake.configureOnOpen": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "git.autofetch": true,
}
- *nodejs version*:Latest
- *vscode version*:Latest
- *extension version*:Latest

**Comment by KevinIrene** [comment]
> ## 🐛 Bug Report
> When I open vscode-Leetcode after updating the latest win11 version in 2021/11/30, I meet an error
>And I have tried reintalling the extension but in vain
> 
> ## To Reproduce
> Just update the version of Windows 11
> 
> ## Expected behavior
> A clear and concise description of what you expected to happen.
> 
> ## Extension Output
> v16.13.0 [ERROR] Plugin not found!
> 
> * Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/company.js
>   (node:16136) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
>   (Use `node --trace-warnings ...` to show where the warning was created)
>   [ERROR] Error: read ECONNRESET
>   Error: Command "node "c:\Users\Chi.vscode\extensions\leetcode.vscode-leetcode-0.18.0\node_modules\vsc-leetcode-cli\bin\leetcode",plugin,-i,company" failed with exit code "1".
> 
> ## Your Environment
> * _os_: Windows11
> * _extension settings_:{
>   "workbench.editorAssociations": {
>   "*.ipynb": "jupyter-notebook"
>   },
>   "python.pythonPath": "C:\Users\Chi\AppData\Local\Programs\Python\Python39\python.exe",
>   "files.autoSave": "afterDelay",
>   "java.home":"D:\JDK",
>   "notebook.cellToolbarLocation": {
>   "default": "right",
>   "jupyter-notebook": "left"
>   },
>   "python.defaultInterpreterPath": "C:\Users\Chi\AppData\Local\Programs\Python\Python39\python.exe",
>   "C_Cpp.updateChannel": "Insiders",
>   "leetcode.nodepath": "D:\Node.js\node.exe",
>   "leetcode.endpoint": "leetcode-cn",
>   "leetcode.workspaceFolder": "D:\my repo\SummerDay\CPP\leetcode",
>   "githubIssues.queries": [
>   {
>   "label": "My Issues",
>   "query": "default"
>   },
>   {
>   "label": "Created Issues",
>   "query": "author:${user} state:open repo:${owner}/${repository} sort:created-desc"
>   }
>   ],
>   "leetcode.defaultLanguage": "cpp",
>   "leetcode.hint.configWebviewMarkdown": false,
>   "leetcode.hint.commentDescription": false,
>   "cmake.configureOnOpen": true,
>   "editor.suggestSelection": "first",
>   "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
>   "files.exclude": {
>   "**/.classpath": true,
>   "**/.project": true,
>   "**/.settings": true,
>   "**/.factorypath": true
>   },
>   "git.autofetch": true,
>   }
> * _nodejs version_:Latest
> * _vscode version_:Latest
> * _extension version_:Latest

**Comment by KevinIrene** [comment]
And I have tried reintalling the extension

**Comment by KevinIrene** [comment]
The output has changed 


v16.13.0
c:\Users\Chi\.vscode\extensions\leetcode.vscode-leetcode-0.18.0\node_modules\vsc-leetcode-cli\lib\plugins\company.js:1455
  '1054': ['math']
                  

SyntaxError: Unexpected end of input
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at c:\Users\Chi\.vscode\extensions\leetcode.vscode-leetcode-0.18.0\node_modules\vsc-leetcode-cli\lib\file.js:66:28
    at Array.map (<anonymous>)
c:\Users\Chi\.vscode\extensions\leetcode.vscode-leetcode-0.18.0\node_modules\vsc-leetcode-cli\lib\plugins\company.js:1455
  '1054': ['math']
                  

SyntaxError: Unexpected end of input
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at c:\Users\Chi\.vscode\extensions\leetcode.vscode-leetcode-0.18.0\node_modules\vsc-leetcode-cli\lib\file.js:66:28
    at Array.map (<anonymous>)
Error: Command "node "c:\Users\Chi\.vscode\extensions\leetcode.vscode-leetcode-0.18.0\node_modules\vsc-leetcode-cli\bin\leetcode",plugin,-i,company" failed with exit code "1".

**Comment by KevinIrene** [comment]
I have figured it out:

What you need to do is delete the filefolder "C:\Users\{$Username$}\.vscode\extensions\leetcode.vscode-leetcode-0.18.0" and delete the extension in vscode  and install it again

**Comment by StevenLiao123** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by EquinoxFlowerJG** [comment]
> I have figured it out:
> 
> What you need to do is delete the filefolder "C:\Users{$Username$}.vscode\extensions\leetcode.vscode-leetcode-0.18.0" and delete the extension in vscode and install it again

I've met the same problem with you, and I try your solution, and it works. Thank you~~

**Comment by CCLONER** [comment]
reinstall is work
