### ISSUE TITLE
VsCode Error: EACCES: permission denied

### ISSUE THREAD

**Issue by gebilaofan** [LeetCode-OpenSource/vscode-leetcode#770]
I log in with China and  `Code Now`

![image](https://user-images.githubusercontent.com/46524158/149617378-0a77862a-55ee-4787-82f3-0c73f1696b0e.png)

Someone can solve the online version of the Chinese version and then withdraw it.  I failed 😔

Environment：
Mac m1  BigSur 11.6.2

Vscode version 1.63

**Comment by gebilaofan** [comment]
Does anyone know?😣

**Comment by sharmilajesupaul** [comment]
what is in the logs when you click "open"?

**Comment by nuynait** [comment]
I'm having the same issue and when look at the log, it says something like cookie expired. Then I choose to do logout, then login with cookie again, this time, I'm no longer able to login with the Cookie. I wrote the issue of my login here.

https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/773#issuecomment-1032679090

**Comment by gebilaofan** [comment]
> I'm having the same issue and when look at the log, it says something like cookie expired. Then I choose to do logout, then login with cookie again, this time, I'm no longer able to login with the Cookie. I wrote the issue of my login here.
> 
> [#773 (comment)](https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/773#issuecomment-1032679090)

I have solved it. My problem is that the Mac user file name is caused.

**Comment by recherst** [comment]
> > I'm having the same issue and when look at the log, it says something like cookie expired. Then I choose to do logout, then login with cookie again, this time, I'm no longer able to login with the Cookie. I wrote the issue of my login here.
> > [#773 (comment)](https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/773#issuecomment-1032679090)
> 
> I have solved it. My problem is that the Mac user file name is caused.

I met the same issue with you, how did you resolve this problem, could you show some details?

**Comment by sunaiwen** [comment]
> > > I'm having the same issue and when look at the log, it says something like cookie expired. Then I choose to do logout, then login with cookie again, this time, I'm no longer able to login with the Cookie. I wrote the issue of my login here.
> > > [#773 (comment)](https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/773#issuecomment-1032679090)
> > 
> > 
> > I have solved it. My problem is that the Mac user file name is caused.
> 
> I met the same issue with you, how did you resolve this problem, could you show some details? @wakaka378

Hi, I just met and solved the same problem. I have vscode installed on my another laptop. And I found that there's a setting called `workspace path` remaining the old value on my another laptop. But the `path` doesn't exist on my current laptop. That's why the problem caused.

**Comment by yjua** [comment]
> > > I'm having the same issue and when look at the log, it says something like cookie expired. Then I choose to do logout, then login with cookie again, this time, I'm no longer able to login with the Cookie. I wrote the issue of my login here.
> > > [#773 (comment)](https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/773#issuecomment-1032679090)
> > 
> > 
> > I have solved it. My problem is that the Mac user file name is caused.
> 
> I met the same issue with you, how did you resolve this problem, could you show some details? @wakaka378

follow the prompts and create a named folder in the user directory with the name it needs.

**Comment by Unequaled804** [comment]
> > > > I'm having the same issue and when look at the log, it says something like cookie expired. Then I choose to do logout, then login with cookie again, this time, I'm no longer able to login with the Cookie. I wrote the issue of my login here.
> > > > [#773 (comment)](https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/773#issuecomment-1032679090)
> > > 
> > > 
> > > I have solved it. My problem is that the Mac user file name is caused.
> > 
> > 
> > I met the same issue with you, how did you resolve this problem, could you show some details? @wakaka378
> 
> Hi, I just met and solved the same problem. I have vscode installed on my another laptop. And I found that there's a setting called `workspace path` remaining the old value on my another laptop. But the `path` doesn't exist on my current laptop. That's why the problem caused.

Thank you! You saved my life!

**Comment by Unequaled804** [comment]
遇到了同样的问题 根据 @sunaiwen  说的把VSCode的settings.json中leetcode相关的字段都干掉了重新配置解决了
