### ISSUE TITLE
vscode远程连接linux后workplace路径仍然使用Windows上路径。

### ISSUE THREAD

**Issue by zyede** [LeetCode-OpenSource/vscode-leetcode#775]
![image](https://user-images.githubusercontent.com/17783147/154023302-d09c0b7b-22c4-4751-a4ec-c0346f9fa0d2.png)
Windows上通过ssh-remote 连接linux后，想使用 leetcode 插件在linux上写算法，但是l默认使用的还是Windows路径，导致 leetcode 插件无法生成代码文件。

于是我尝试在工作区中改写设置，发现 leetcode 相关的设置只能在用户设置中才能生效
![image](https://user-images.githubusercontent.com/17783147/154024040-5e0288b0-9ba7-4bf2-a9d3-ea64a8e57a9a.png)

请问有什么方法能让我的 vscode 能远程访问 linux 并且能在 linux 上使用 leetcode 插件？

不胜感激！

**Comment by zyede** [comment]
> ![image](https://user-images.githubusercontent.com/17783147/154023302-d09c0b7b-22c4-4751-a4ec-c0346f9fa0d2.png) Windows上通过ssh-remote 连接linux后，想使用 leetcode 插件在linux上写算法，但是l默认使用的还是Windows路径，导致 leetcode 插件无法生成代码文件。
> 
> 于是我尝试在工作区中改写设置，发现 leetcode 相关的设置只能在用户设置中才能生效 ![image](https://user-images.githubusercontent.com/17783147/154024040-5e0288b0-9ba7-4bf2-a9d3-ea64a8e57a9a.png)
> 
> 请问有什么方法能让我的 vscode 能远程访问 linux 并且能在 linux 上使用 leetcode 插件？
> 
> 不胜感激！

解决了
![image](https://user-images.githubusercontent.com/17783147/154026596-9ff08fe0-9320-42bb-93c0-346f7fd43c1d.png)
原来只需要分别为不同的系统写上对应的路径就可以自动使用可用的设置。
虽然 vscode 会报警hhh。

**Comment by ryougishikifor214** [comment]
2025年了 vscode leetcode插件还是不能 单独设置remote
还是得这样子
