### ISSUE TITLE
Feature: Need to add a new domain name

### ISSUE THREAD

**Issue by Chever-John** [LeetCode-OpenSource/vscode-leetcode#797]
## 🚀 Feature Proposal

I recently discovered that the official domain name of leetcode has changed from leetcode-cn.com to leetcode.cn. This means that the plugin needs to be transformed, and I'm willing to help if I can~

behavior: #798 #799 

## Motivation

If you don't change it, the Chinese leetcode will not be available anymore.

## Contribution

I will add a new domain name in this [file](https://github.com/LeetCode-OpenSource/vscode-leetcode/blob/de1dc4161b497b4f76faad2363abab0104a75373/src/commands/plugin.ts#:~:text=description%3A%20%22leetcode%2Dcn.com%22%2C)

**Comment by labuladong** [comment]
是域名的问题，我基于官方插件修改的版本修复了这个问题，详情看这里：[labuladong 的 vscode 刷题插件](https://mp.weixin.qq.com/s/z4mqiiJV9pZ3t6SIPa2kTA)

**Comment by Chever-John** [comment]
@labuladong Yes, it is indeed a problem with the domain name. Thank you for contributing such a good plugin, I'll try it out. Also hope the official can modify the project soon.

**Comment by Chever-John** [comment]
This [link](https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/799#issuecomment-1120721770) solves the problem; just replace the domain name.
Of course, I would still like to submit a PR to solve this problem and ask the official to take care of this issue. I am willing to contribute to it.

**Comment by Miloas** [comment]
try 0.18.1, feel free reopen issue if it wont resolve your issue
