### ISSUE TITLE
点击 Test 出错 [ERROR] http error [code=301]

### ISSUE THREAD

**Issue by doubley318** [LeetCode-OpenSource/vscode-leetcode#799]
可以通过VScode登录leetcode，也可以刷新题目的列表，但是当我写好代码之后点击测试(`Test`)，就会出错：
```bash
- Sending code to judge
(node:6604) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] http error [code=301]
```
<img width="643" alt="image" src="https://user-images.githubusercontent.com/95672897/167334207-e33c2a5f-5bdf-49ac-9a32-66f3fade7cb4.png">
点击提交(`Submit`)，也无法出现正确的画面：
<img width="926" alt="image" src="https://user-images.githubusercontent.com/95672897/167334417-cae7f0d3-bbe7-4d13-a4e8-d462fe034457.png">
怎么解决呢？

**Comment by GitHubQAQ** [comment]
出现了同样的问题，然后退出账号之后就登不上了。可能是leetcode.cn也改变了登录验证机制吧

**Comment by scientiacoder** [comment]
+1 相同问题

**Comment by labuladong** [comment]
是登录域名的问题，我基于官方插件修改的版本修复了这个问题，详情看这里：[labuladong 的 vscode 刷题插件](https://mp.weixin.qq.com/s/z4mqiiJV9pZ3t6SIPa2kTA)

**Comment by beiyouwuyanzu** [comment]
me too.

**Comment by wy-luke** [comment]
> 是登录域名的问题，我基于官方插件修改的版本修复了这个问题，详情看这里：[labuladong 的 vscode 刷题插件](https://mp.weixin.qq.com/s/z4mqiiJV9pZ3t6SIPa2kTA)

讲真，东哥这插件挺好用的，添加了挺多好用的小功能

**Comment by Lyncien** [comment]
可以临时修改 `%home%\.vscode\extensions\leetcode.vscode-leetcode-0.18.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.cn.js` 文件，替换配置中所有的 `https://leetcode-cn.com` 为 `https://leetcode.cn` 即可正常提交

**Comment by Chever-John** [comment]
@Lyncien This solution works!

**Comment by doubley318** [comment]
> 可以临时修改 `%home%\.vscode\extensions\leetcode.vscode-leetcode-0.18.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.cn.js` 文件，替换配置中所有的 `https://leetcode-cn.com` 为 `https://leetcode.cn` 即可正常提交

太强了！！！

**Comment by bhllssjdhj** [comment]
> 
vim用户见下：
':1,$s/word1/word2/g：将全文的word1替换为word2'

**Comment by 9939zhonghuajia** [comment]
> 可以临时修改 `%home%\.vscode\extensions\leetcode.vscode-leetcode-0.18.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.cn.js` 文件，替换配置中所有的 `https://leetcode-cn.com` 为 `https://leetcode.cn` 即可正常提交

那请问一下怎么修改

**Comment by Chever-John** [comment]
@9939zhonghuajia It is clear! Which OS do you use?

**Comment by 9939zhonghuajia** [comment]
> @9939zhonghuajia It is clear! Which OS do you use?

windows

**Comment by Chever-John** [comment]
> > @9939zhonghuajia It is clear! Which OS do you use?
> 
> windows

If it were me, I would choose to use the everything tool to find the configuration file I should change, as shown in this reply.
Then modify it~

**Comment by 9939zhonghuajia** [comment]
> 

那你解决这个问题了嘛。By the way，did you solve the problem？？

**Comment by Chever-John** [comment]
@9939zhonghuajia 
I managed to solve the problem on my macOS.
