### ISSUE TITLE
http error 301 when test code (using default cases)

### ISSUE THREAD

**Issue by Neil-Gao** [LeetCode-OpenSource/vscode-leetcode#801]
## log details:

- Sending code to judge
(node:77934) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] http error [code=301]

**Comment by MingKaiWang** [comment]
I have same question

**Comment by xiaozeiqwe8** [comment]
I have same question

**Comment by zzeitt** [comment]
This (https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/799#issuecomment-1120721770) addressed the problem.

**Comment by Miloas** [comment]
try 0.18.1, feel free reopen issue if it wont resolve your issue
