### ISSUE TITLE
when i submit or test code,  i get error that http error  code=301

### ISSUE THREAD

**Issue by MingKaiWang** [LeetCode-OpenSource/vscode-leetcode#803]
Sending code to judge [ERROR] http error [code=301]

**Comment by MingKaiWang** [comment]
![image](https://user-images.githubusercontent.com/23495279/167383879-34db2907-9dd0-4edc-b3a4-33e1ae2fa3f0.png)

**Comment by zzeitt** [comment]
This (https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/799#issuecomment-1120721770) addressed the problem.

**Comment by Miloas** [comment]
try 0.18.1, feel free reopen issue if it wont resolve your issue
