### ISSUE TITLE
can't login leetcode

### ISSUE THREAD

**Issue by xiaozeiqwe8** [LeetCode-OpenSource/vscode-leetcode#804]
I try login and the console show:
pass: - Signing in leetcode-cn.com
[ERROR] invalid password?

I sure my password and count is correct

**Comment by yxw007** [comment]
+1

**Comment by zzeitt** [comment]
This (https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/799#issuecomment-1120721770) addressed the problem.

**Comment by Miloas** [comment]
try 0.18.1, feel free reopen issue if it wont resolve your issue

**Comment by yxw007** [comment]
> This ([#799 (comment)](https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/799#issuecomment-1120721770)) addressed the problem.

thanks
