### ISSUE TITLE
Failed to submit successfully

### ISSUE THREAD

**Issue by CrazyCatZhang** [LeetCode-OpenSource/vscode-leetcode#826]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/67346540/180646307-c21c386c-e85f-4558-84f1-8f6c6df37062.png">

**Comment by ShaalanMarwan** [comment]
+1
same problem

**Comment by CrazyCatZhang** [comment]
Logging in with cookies can solve this problem

**Comment by CrazyCatZhang** [comment]
Logging in with a cookie solves the problem

**Comment by CrazyCatZhang** [comment]
> +1 same problem

Logging in with a cookie solves the problem

**Comment by ShaalanMarwan** [comment]
should I log out and log in again?

**Comment by ShaalanMarwan** [comment]
> should I log out and log in again?


should I log out and log in again?

**Comment by CrazyCatZhang** [comment]
> > should I log out and log in again?
> 
> should I log out and log in again?

yep
