### ISSUE TITLE
Problem id higher than 2127 doesn't show and cannot found.

### ISSUE THREAD

**Issue by abietic** [LeetCode-OpenSource/vscode-leetcode#850]
I want to solve problem 2376 but found out that the extension only have 2127 problems.
![image](https://user-images.githubusercontent.com/25390418/196627494-70b4bd03-5903-47c2-aa04-b765064d5ed2.png)

![image](https://user-images.githubusercontent.com/25390418/196627381-c38c5f65-6bbb-4064-a3f4-a98da5ad624a.png)

So I tried to create my own file to cope with this problem. 

![image](https://user-images.githubusercontent.com/25390418/196627717-a5890c33-947f-4dc5-92c9-a3ad99c7b97c.png)

But it doesn't work with error.

![image](https://user-images.githubusercontent.com/25390418/196627854-b8eb89bf-3507-4820-a3bd-a6a6d508ec11.png)

**Comment by zinbiel576** [comment]
Yeah, I can confirm I'm getting the same issue

**Comment by abietic** [comment]
I tried but nothing changed, by the way i use third party login with github account to login leetcode.com.

**Comment by genment** [comment]
Have you tried to refresh your list by clicking the "Refresh" button above the problem list?

**Comment by abietic** [comment]
I update the node version to v18.12.1 and reset all settings in extension. The extension now works fine.
![image](https://user-images.githubusercontent.com/25390418/205579914-8520c200-0434-4efe-90f0-3a2e19508fd4.png)
