### ISSUE TITLE
Error: ENOENT: no such file or directory, mkdir '\\?' Please open the output channel for details.

### ISSUE THREAD

**Issue by Lacia-I** [LeetCode-OpenSource/vscode-leetcode#865]
The problem was appeared suddenly. 
When I click the button 'Code Now', this error will show right now.
I don't know why the error show: mkdir '\\?' .
How to fix the problem?

**Comment by Projecthappy** [comment]
I have the same problem as you. I ran "node --trace-warnings ..." in command, and it returns this result: 
```
Debugger attached.
Waiting for the debugger to disconnect...
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'G:\Code\leetcode\...'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
'G:\Code\leetcode\...' is my working directory

**Comment by Projecthappy** [comment]
I read this issue and solved the problem. #742 
In the original settings, my working directory is 'G:\Code\leetcode'. It is synchronized from the settings of another computer.
I set the local settings to correct and it works normally.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/76643786/224488714-9ad43333-5964-4228-9e8b-8edfb3653217.png">

**Comment by Lacia-I** [comment]
> 

NICE! Thank you! I also have two computers, and vscode syncs the paths with different root directories from the other computer. Now I solve the problem.

**Comment by Lacia-I** [comment]
> I read this issue and solved the problem. #742 In the original settings, my working directory is 'F:\Code\leetcode'. It is synchronized from the settings of another computer. I set the local settings to correct and it works normally.
> 
> <img alt="image" width="405" src="https://user-images.githubusercontent.com/76643786/224488714-9ad43333-5964-4228-9e8b-8edfb3653217.png">
NICE! Thank you! I also have two computers, and vscode syncs the paths with different root directories from the other computer. Now I solve the problem.
