### ISSUE TITLE
Can't test or submit code

### ISSUE THREAD

**Issue by ThangNguyen23** [LeetCode-OpenSource/vscode-leetcode#926]
## 🐛 Bug Report

I can't test or submit code when using the plugin. It's still undefined.

**Comment by MakiseJ** [comment]
Same issue, besides I cannot login by github since this morning.
login: (node:20320) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: [ERROR] Login failed. Please make sure the credential is correct.

**Comment by Imran7junior** [comment]
I'm also facing this issue from yesterday. 
Output- `- Waiting session result
(node:7148) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] session expired, please login again [code=-1]`
After running `node --trace-warnings ...`. I get the following:
`node --trace-warnings ...
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'D:\Coding\DSA\...'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.10.0`
Also I tried login using cookie method which I always do

**Comment by woung717** [comment]
Check [here](https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/927#issuecomment-1986832815)

**Comment by rachelxhoot** [comment]
> Check [here](https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/927#issuecomment-1986832815)

it works, thank you!

**Comment by leozhao21** [comment]
It resolved, related comment [!928](https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/928#issuecomment-2005679295)
