### ISSUE TITLE
Cannot open problem page

### ISSUE THREAD

**Issue by 943n** [LeetCode-OpenSource/vscode-leetcode#928]
## 🐛 Bug Report

When I open the leetcode extension tab and click on any problem, it does not open the problem page but shows : Command "node "/home/n349/.vscode-oss/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/bin/leetcode",show,11,-x" failed with exit code "0". 

## To Reproduce

Steps to reproduce the behavior.

## Expected behavior

Open the clicked problem description page

## Extension Output

Command "node "/home/n349/.vscode-oss/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/bin/leetcode",show,3,-x" failed with exit code "0".

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.

## Your Environment

- *os*: fedora 39
- *extension settings*: Default
- *nodejs version*: v20.10.0
- *vscode version*: 1.87.0
- *extension version*: v0.18.1

**Comment by woung717** [comment]
Check [here](https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/927#issuecomment-1986832815)

**Comment by Lakhwinderr** [comment]
Yeah, I am also facing the same problem. Can't load problems list.

Downloading problems
(node:7424) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] session expired, please login again [code=-1]

**Comment by leozhao21** [comment]
We changed some API policies, now it worked,
