### ISSUE TITLE
Can't load the problem list

### ISSUE THREAD

**Issue by Lakhwinderr** [LeetCode-OpenSource/vscode-leetcode#930]
## 🐛 Bug Report

I successfully logged in to the extension but there is an error in loading the questions list.

## Extension Output

Downloading problems
(node:7424) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] session expired, please login again [code=-1]

os: windows 10
extension settings: Default
nodejs version: v16.13.1
vscode version: 1.87.1
extension version: v0.18.1

**Comment by fym202** [comment]
我也有这个问题（I have this problem too.）
Node.js v20.11.0
(node:21112) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
login: (node:26856) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by SkyeSun** [comment]
Similar problem: Failed to load problem list after logging in, refreshing also didn't work.
#### Error msg
```
- Downloading problems
(node:13207) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13207) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
[ERROR] Error: read ECONNRESET
```
#### Environment
```
os: MacOS Monterey(12.3)
extension settings: Default
nodejs version: v16.18.1
vscode version: 1.87.2
extension version: v1.5.3
```

**Comment by leozhao21** [comment]
Resolved
