### ISSUE TITLE
Cannot test or submit code

### ISSUE THREAD

**Issue by LeoLee53** [LeetCode-OpenSource/vscode-leetcode#934]
## 🐛 Bug Report

I can see the problem, load the set up and start writing code solutions, but once I'm done and try to test or solve it, it gave me error.

## To Reproduce

Simply log in using cookie and tried to test your solution for any problem should reproduce the issue.

## Extension Output

- Sending code to judge
(node:30513) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] session expired, please login again [code=-1]

## Your Environment

- *os*: macOS Sonoma 14.4
- *extension settings*: default setting
- *nodejs version*: 18.16.0
- *vscode version*: 1.87.2
- *extension version*: 0.18.1

**Comment by leozhao21** [comment]
It worked for US

**Comment by leozhao21** [comment]
It worked for US

**Comment by LeoLee53** [comment]
That did not work for ME. Try being helpful :)

**Comment by LeoLee53** [comment]
> It worked for US

That did not work for ME. Try being helpful bro.
