### ISSUE TITLE
(SOLVED) Please help me: Can't load any questions and test, submit

### ISSUE THREAD

**Issue by fanzhangvivian** [LeetCode-OpenSource/vscode-leetcode#953]
Hi, everyone! I met a weird problem!
I can choose the button to sign in and open the browser to continue, but I can't load any questions. And I also tried some previous versions of node.js like 17.9.1, 13.4.0.... it still didn't work. Could you help me to fix the issues? Thank you!

>I can click sign in like this
![image](https://github.com/LeetCode-OpenSource/vscode-leetcode/assets/132254781/3fc78e8a-ed1c-4262-a85e-09233cc808fa)

> but I can't load any question.
![image](https://github.com/LeetCode-OpenSource/vscode-leetcode/assets/132254781/277e5c1a-4d63-476e-b3f2-6afe71603ab9)

> My environment:
vscode version: 1.89.1
leetcode version: 0.18.2
node.js version: 20.14.0

**Comment by 3000-codes** [comment]
安装回0.18.1吧

**Comment by fanzhangvivian** [comment]
> 安装回0.18.1吧

我试了，也不行

**Comment by fanzhangvivian** [comment]
> 安装回0.18.1吧

谢谢！安装回0.18.1 用cookie登录又可以了

**Comment by leozhao21** [comment]
Previously, the leetcode plugin could not be invoked to log in to Windows. This has been fixed
