### ISSUE TITLE
不能登录leetcode.cn

### ISSUE THREAD

**Issue by Neymar-10-JR** [LeetCode-OpenSource/vscode-leetcode#954]
Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] You are not login yet?
(node:80752) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by lvkanu** [comment]
我也是相同问题

**Comment by DrLemonn** [comment]
一样的问题

**Comment by qiuyuleng** [comment]
Change to old version

**Comment by Aseisman** [comment]
解决了么老铁们

**Comment by Candysad** [comment]
- 2024/5/15 更新之后登录变成点击跳转到主站然后跳转回vscode，但是我这里最后一步跳转不回来，vscode里没反应
- 插件更新之前登录不了是因为主站登录策略发生变化，不能在插件里用账户密码登录
- 但是还可以用 cookie 登录
- 目前的解决方法是
    - 换回[0.18.1版本](https://marketplace.visualstudio.com/items?itemName=LeetCode.vscode-leetcode)
    - 下好了打开vscode扩展栏，把 vsix 拖进拓展栏里
    - 用 cookie 登录

**Comment by leozhao21** [comment]
已修复，window 系统已经可以正常唤起 vscode 插件登录了，如果不能完成登录，可以尝试卸载插件重新连接
