### ISSUE TITLE
Unable to login using the default login method in vscode-insiders

### ISSUE THREAD

**Issue by yuzujr** [LeetCode-OpenSource/vscode-leetcode#966]
## 🐛 Bug Report

Unable to login using the default login method in **vscode-insiders**

## To Reproduce

After authorizing the login in the browser it tries to open vscode to complete the authentication，the URL is like "vscode://leetcode.vscode-leetcode?&cookie=**your cookie**".
If you are using vscode-insiders, nothing will happen when clicking the button or visiting the URL

## Expected behavior

Successfully return to vscode to complete authentication login

## Extension Output

None，Because the browser cannot return to vscode

## Your Environment

- *os*: Windows 11 Insider Preview 23H2
- *extension settings*: default
- *nodejs version*: v22.2.0
- *vscode version*: 1.92.0-insider
- *extension version*: 0.18.2

## Solution
change the URL to "vscode-insiders://leetcode.vscode-leetcode?&cookie=**your cookie**" manually.
This way the computer can correctly identify the URL and open vscode.

**Comment by BETTlM** [comment]
You can't login even if you use VS Code by the regular login method. Refer This:

https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/964

**Comment by yuzujr** [comment]
> You can't login even if you use VS Code by the regular login method. Refer This:
> 
> #964

well, in fact I fix this by "change the URL to "vscode-insiders://leetcode.vscode-leetcode?&cookie=your cookie" manually.
This way the computer can correctly identify the URL and open vscode."
So sign in by "Leetcode Account" works for me.
I use Windows, situation might be different on Linux.

**Comment by BETTlM** [comment]
> > You can't login even if you use VS Code by the regular login method. Refer This:
> > #964
> 
> well, in fact I fix this by "change the URL to "vscode-insiders://leetcode.vscode-leetcode?&cookie=your cookie" manually. This way the computer can correctly identify the URL and open vscode." So sign in by "Leetcode Account" works for me. I use Windows, situation might be different on Linux. Where are you stuck by "Leetcode Account"？

after opening vscode from the browser, it will get struck on 'fetching user data' forever, and for that, this was the solution
